### ISSUE TITLE
Carga de más de una foto

### ISSUE THREAD

**Issue by diana-bohorquez** [icsred/chatbot-obras#3]
El script realizado hasta la fecha contiene pedir una foto por item. Se debe:

- [ ] Habilitar al usuario subir más de una foto
- [ ] El script, creo, pide secuencialmente las fotos. Se debería poder subir fotos nuevas fotos de items que ya se cargaron.
- [ ] Si se ha cargado una foto, poder eliminarla o etiquetarla como que se cargó por error.

**Comment by marceicsred** [comment]
Solucionado!!
